export const defaulttasklist = {
    "folha": {
        "Cadastros e correções": true,
        "Mensalista": true,
        "Prolaborista": true,
        "Horista especial": false,
        "Criar verbas específicas": true,
        "Autônomo": false,
        "Empresa concomitante do SN": false,
        "Empresa PBM": false,
        "Empresa com departamentos": false,
        "Empresa com centros de custo": false,
        "Folha rateada entre tomadores": false,
        "Visual Pontual": false,
        "Plano de saúde": false,
        "Cálculos": true,
        "Relatórios e recibos": true,
        "e-Social": true,
        "Auditor e-Social": true,
        "Módulo SST": false,
        "SChIp": true,
        "SEFIP e DARF IR": true,
        "Exportação para Sucessor": true,
        "Utilitários e opções de segurança": true,
    },
    "fiscal": {
        "Simples Nacional " : true,
        "Lucro Presumido" : false,
        "Lucro Real" : false,
        "Integração Sistemas SCI" : true,
        "Inventarium " : false,
        "DIME - Crédito Presumido" : false,
        "DRCST - Comp. e Restituição de ICMS ST" : false,
    },
    "contábil": {
        "Treinamento Básico": true,
        "Lalur SCI Visual Pronto ": false,
        "Pâtrimonio SCI  Visual Ativa": false,

    },
    "financeiro": {
        "Treinamento completo" : false,
        "Tira Dúvidas" : false,
    },
    "tarefas": {
        "Push SCI 2.0" : false,
        "Instalação Push" : false,
        "ISS Legal SCI" : false,
        "RH NET Social" : false,
        "Integra NET" : false,
        "SBS - Smart Bank Statement" : false,
        "SCI Report - Serviços 24H" : false,
        "SCI Report - Tarefas" : false,
        "SCI Report - Atendimento" : false,
        "SCI Report - CND" : false,
        "Dasboard SCI" : false,
        "SCI Print PDF" : false,
        "Agente SCI" : false,
        "SCI App 4.0" : false,
    },
    "orcamentos": {
        "Push SCI 2.0" : false,
        "Instalação Push" : false,
        "ISS Legal SCI" : false,
        "RH NET Social" : false,
        "Integra NET" : false,
        "SBS - Smart Bank Statement" : false,
        "SCI Report - Serviços 24H" : false,
        "SCI Report - Tarefas" : false,
        "SCI Report - Atendimento" : false,
        "SCI Report - CND" : false,
        "Dasboard SCI" : false,
        "SCI Print PDF" : false,
        "Agente SCI" : false,
        "SCI App 4.0" : false,
    },
    "protocolos": {
        "Push SCI 2.0" : false,
        "Instalação Push" : false,
        "ISS Legal SCI" : false,
        "RH NET Social" : false,
        "Integra NET" : false,
        "SBS - Smart Bank Statement" : false,
        "SCI Report - Serviços 24H" : false,
        "SCI Report - Tarefas" : false,
        "SCI Report - Atendimento" : false,
        "SCI Report - CND" : false,
        "Dasboard SCI" : false,
        "SCI Print PDF" : false,
        "Agente SCI" : false,
        "SCI App 4.0" : false,
    },
    "notificações": {
        "Push SCI 2.0" : false,
        "Instalação Push" : false,
        "ISS Legal SCI" : false,
        "RH NET Social" : false,
        "Integra NET" : false,
        "SBS - Smart Bank Statement" : false,
        "SCI Report - Serviços 24H" : false,
        "SCI Report - Tarefas" : false,
        "SCI Report - Atendimento" : false,
        "SCI Report - CND" : false,
        "Dasboard SCI" : false,
        "SCI Print PDF" : false,
        "Agente SCI" : false,
        "SCI App 4.0" : false,
    },
}