export const tasklist = {
    "practice": {
        "Cadastros e correções": 2,
        "Mensalista": 1,
        "Prolaborista": 0.5,
        "Horista especial": 1,
        "Criar verbas específicas": 1,
        "Autônomo": 0.5,
        "Empresa concomitante do SN": 1,
        "Empresa PBM": 0.5,
        "Empresa com departamentos": 0.5,
        "Empresa com centros de custo": 0.5,
        "Folha rateada entre tomadores": 1,
        "Visual Pontual": 1,
        "Plano de saúde": 1,
        "Cálculos": 1,
        "Relatórios e recibos": 0.25,
        "e-Social": 2,
        "Auditor e-Social": 0.25,
        "Módulo SST": 0.25,
        "SChIp": 0.25,
        "SEFIP e DARF IR": 0.25,
        "Exportação para Sucessor": 0.25,
        "Utilitários e opções de segurança": 0.25,
    },
    "suprema": {
        "Simples Nacional " : 2,
        "Lucro Presumido" : 2.5,
        "Lucro Real" : 2.5,
        "Integração Sistemas SCI" : 1,
        "Inventarium " : 1,
        "DIME - Crédito Presumido" : 1,
        "DRCST - Comp. e Restituição de ICMS ST" : 1,
    },
    "sucessor": {
        "Treinamento Básico": 2,
        "Lalur SCI Visual Pronto ": 1,
        "Pâtrimonio SCI  Visual Ativa": 1,

    },
    "controller": {
        "Treinamento completo" : 2,
        "Tira Dúvidas" : 1,
    },
    "web": {
        "Push SCI 2.0" : 1,
        "Instalação Push" : 1,
        "ISS Legal SCI" : 1,
        "RH NET Social" : 2,
        "Integra NET" : 1,
        "SBS - Smart Bank Statement" : 1.5,
        "SCI Report - Serviços 24H" : 2,
        "SCI Report - Tarefas" : 1,
        "SCI Report - Atendimento" : 0.5,
        "SCI Report - CND" : 0.5,
        "Dasboard SCI" : 1,
        "SCI Print PDF" : 0.5,
        "Agente SCI" : 0.5,
        "SCI App 4.0" : 0.5,
    }
}